### PR TITLE
hi

### PR DESCRIPTION
**Pull request by corason331**
hey

### CODE REVIEW

**Comment by Lordmau5** [comment]
Hi 🙂

**Comment by corason331** [comment]
i dont know if am doin it right so sorry from the begin

**Comment by Lordmau5** [comment]
Okay, then let me ask this:
What did you try to do? Why is the title of this Pull Request only "hi", the text is "hey" and the commits you are trying to merge are... commits that are already in the code, as in, why didn't you do any changes?

**Comment by corason331** [comment]
i dont know what exacly am doing am i think am trying though i dont have
anyone teaching me sorry

**Comment by Lordmau5** [comment]
If you're new to GitHub or Git as a whole, this might be interesting to you :)
https://guides.github.com/activities/hello-world/

**Comment by corason331** [comment]
tryied to put my patreon emote

**Comment by Lordmau5** [comment]
If you need some help in that regard, please join the Discord and ask in there - GitHub isn't the place for this

https://discord.ffzap.com/

**Comment by corason331** [comment]
thanks

**Pull request closed without merging**
